spring.application.name=heritage_sharing_platform
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://118.178.124.2:3306/heritage_sharing_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
# spring.datasource.url=jdbc:mysql://localhost:3306/heritage_sharing_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
spring.datasource.username=root
spring.datasource.password=D7ztnbl.
# spring.datasource.password=FB1f_26540330

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.port=8080

# Redis Configuration
spring.redis.host=118.178.124.2
spring.redis.port=6379
spring.redis.password=root
spring.redis.timeout=60000